version: "3.9"

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
  app:
    build: .
    command: ["node", "build/index.js"]
    env_file:
      - ./test.env
    ports:
      - 8000:8000
    depends_on:
      - mongodb
